# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
d = np.reshape(arr, (2, 5))
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
c= np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
c= np.hstack((a,b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
a = np.array([[0,1,2,3,4], [5,6,7,8,9]])

b = a.ravel()
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
a = np.array([[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14]])
np.shape(a)
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [25]:
arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14])

n = arr.reshape(5, 3)

print(n)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
arr = np.random.random_sample((5, 5))*10
print(arr)
np.square(arr)

[[1.75720515 0.73533248 9.75982535 6.11710996 7.38901921]
 [4.2364883  1.77891659 0.81461607 5.37953305 7.77074534]
 [7.92912276 6.72512129 0.19060378 5.97047067 9.26285441]
 [0.79382765 1.94598108 7.01619737 0.90197436 7.88157034]
 [1.05570367 0.64370859 1.25551933 1.98501712 9.33512272]]


array([[3.08776995e+00, 5.40713862e-01, 9.52541909e+01, 3.74190342e+01,
        5.45976048e+01],
       [1.79478332e+01, 3.16454422e+00, 6.63599341e-01, 2.89393759e+01,
        6.03844831e+01],
       [6.28709878e+01, 4.52272564e+01, 3.63297997e-02, 3.56465200e+01,
        8.58004718e+01],
       [6.30162341e-01, 3.78684237e+00, 4.92270255e+01, 8.13557749e-01,
        6.21191510e+01],
       [1.11451023e+00, 4.14360746e-01, 1.57632879e+00, 3.94029298e+00,
        8.71445162e+01]])

## Question:8

### Create 5x6 an array and find the mean?

In [30]:
arr = np.random.random_sample((5, 6))*10
print(arr)
np.mean(arr)

[[2.30328667 9.25627086 9.47528646 1.14220336 7.21950819 0.8711327 ]
 [6.48644127 1.61477261 5.85460066 5.53140051 2.0437345  3.60908325]
 [4.26479676 6.35687246 5.31936063 4.5805518  9.89478944 0.65686232]
 [7.30653048 1.79362511 0.15225047 5.71602538 0.15912327 3.50312248]
 [2.12589282 2.86004745 6.89590631 4.3072128  5.8675319  1.25468862]]


4.280763718109774

## Question:9

### Find the standard deviation of the previous array in Q8?

In [32]:

np.std(arr)

2.796273936035827

## Question:10

### Find the median of the previous array in Q8?

In [33]:
np.median(arr)

4.286004781128048

## Question:11

### Find the transpose of the previous array in Q8?

In [34]:
np.transpose(arr)

array([[2.30328667, 6.48644127, 4.26479676, 7.30653048, 2.12589282],
       [9.25627086, 1.61477261, 6.35687246, 1.79362511, 2.86004745],
       [9.47528646, 5.85460066, 5.31936063, 0.15225047, 6.89590631],
       [1.14220336, 5.53140051, 4.5805518 , 5.71602538, 4.3072128 ],
       [7.21950819, 2.0437345 , 9.89478944, 0.15912327, 5.8675319 ],
       [0.8711327 , 3.60908325, 0.65686232, 3.50312248, 1.25468862]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [37]:
arr = np.random.random_sample((4,4))*10
print(arr)
t = np.trace(arr)
t

[[5.10481088 5.60861142 5.8946022  6.65203854]
 [5.98880821 5.43271403 1.97444103 2.93662264]
 [7.49734601 2.01921207 5.41475095 7.89195838]
 [0.2797232  5.72453543 3.24372435 3.31522092]]


19.2674967710863

## Question:13

### Find the determinant of the previous array in Q12?

In [40]:
np.linalg.det(arr)

-167.4921120115229

## Question:14

### Find the 5th and 95th percentile of an array?

In [45]:
a=np.percentile(arr, 5)
print(a)
b=np.percentile(arr, 95)
print(b)

1.5507615750660881
7.595999100733511


## Question:15

### How to find if a given array has any null values?

In [48]:
np.isnan(arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])