# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np 

2. Create a null vector of size 10 

In [2]:
x = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [5]:
y = np.arange(10,49)

4. Find the shape of previous array in question 3

In [6]:
np.shape(y)

(39,)

5. Print the type of the previous array in question 3

In [9]:
type(y)

numpy.ndarray

6. Print the numpy version and the configuration


In [10]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

7. Print the dimension of the array in question 3


In [14]:
y.ndim

1

8. Create a boolean array with all the True values

In [17]:
z=np.ones((2, 2), dtype=bool)

9. Create a two dimensional array




In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])

10. Create a three dimensional array



In [21]:
a = np.array([[1, 2, 3], [4, 5, 6],[4, 5, 6]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [27]:
x=np.array([1,2,3])
print(x)
y = x[::-1]
y

[1 2 3]


array([3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [29]:
b=np.array([int(x==4) for x in range(10)])
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [31]:
D=np.identity(3)
D

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype('f')

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [40]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [43]:
aj=np.intersect1d(arr1, arr2)
aj

array([1., 2., 4.])

17. Extract all odd numbers from arr with values(0-9)

In [48]:
od=arr[arr % 2 == 1]

18. Replace all odd numbers to -1 from previous array

In [51]:
arr[arr%2 == 1] = -1 
arr

array([-1,  2, -1,  4, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [54]:
arr = np.arange(10)
np.put(arr, [5, 6,7,8], [12])
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [57]:
x = np.ones((8,8))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [62]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
np.put(arr2d, [4], [12])
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [75]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0]=64
arr3d

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [83]:
arr2d =np.arange(0,9).reshape(3,3)
arr2d[0]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [87]:
arr2d =np.arange(0,9).reshape(3,3)
arr2d[1,1]

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [102]:
arr2d =np.arange(0,9).reshape(3,3)
print(arr2d[0,2])
print(arr2d[1,2])

2
5


26. Create a 10x10 array with random values and find the minimum and maximum values

In [103]:
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[4.87236101e-01 9.13283625e-01 6.73578518e-01 5.38369783e-01
  9.49847880e-01 8.68176864e-01 6.76241030e-01 9.02596987e-02
  2.93383196e-01 1.03921747e-01]
 [6.13054918e-02 8.23385002e-01 1.82453951e-02 5.08834072e-01
  1.77125913e-01 6.27685227e-01 5.14777241e-01 6.28378190e-01
  6.39471049e-01 4.90441847e-01]
 [7.76454690e-01 7.72719737e-01 3.41011898e-01 7.65110169e-01
  5.32783835e-01 2.74633997e-01 5.20743775e-01 3.07674172e-01
  5.36283450e-01 8.60988739e-01]
 [7.61807838e-01 9.07393130e-01 5.33134528e-01 8.67756094e-05
  7.31730346e-01 4.15022218e-01 1.37897863e-01 5.52395085e-01
  7.49850165e-01 1.91925783e-01]
 [8.63019742e-01 4.02938614e-01 9.90363069e-01 1.27555645e-01
  1.22611569e-02 7.53383848e-01 6.54979669e-01 6.13389781e-01
  7.32294920e-01 8.61423588e-01]
 [3.88772415e-01 6.40041016e-01 2.46353040e-01 5.83960097e-01
  4.91387834e-01 6.79817651e-01 6.00214122e-01 3.89288376e-01
  5.77496199e-01 2.28417840e-01]
 [1.87312330e-01 6.09460978e-01 7.51043183e-01 4.62214130e

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [105]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [113]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))[0]

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [117]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names != 'Will']

array([[-3.00284851,  1.16597497, -0.27821497, -1.07906184],
       [ 0.37604903, -0.46886979, -0.28293145,  0.40594995],
       [-0.75640099, -1.06868824, -1.3006146 , -0.63588195],
       [-0.55305192, -0.65056575,  0.37819044,  0.77846872],
       [-1.18654757,  0.17979306,  0.36162834, -0.63819092]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [125]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
a=data[names != 'Will']
a=data[names != 'Joe']
a


array([[-2.2853547 , -0.45623595,  0.74056211,  0.60479375],
       [ 1.44001189, -0.2881409 , -1.77883367, -0.08404483],
       [ 0.46699923,  1.88611189,  0.02692015, -1.01416638],
       [-0.07975146, -1.11681824,  0.2323229 ,  0.58886394]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [137]:
arr = np.random.uniform(1,15, size=(5,3))
arr

array([[ 5.9476326 ,  4.03666783,  7.75121163],
       [ 7.71484297,  1.06647949, 10.24730259],
       [10.98319917,  5.81430312, 12.65426151],
       [ 6.9633883 ,  8.41104628,  4.43306261],
       [10.72237731,  1.99568904,  8.77152044]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [138]:
arr = np.random.uniform(1,16, size=(2,2,4))
arr

array([[[ 5.34278467,  2.12148946,  2.7202716 ,  7.96485388],
        [10.59687086,  8.81358771, 15.40464332, 10.39030825]],

       [[ 4.24578258, 14.29431475, 15.75922854,  5.56421522],
        [13.10416067, 11.9337243 ,  7.37750935, 13.8306591 ]]])

In [139]:
np.swapaxes(arr,0,1)

array([[[ 5.34278467,  2.12148946,  2.7202716 ,  7.96485388],
        [ 4.24578258, 14.29431475, 15.75922854,  5.56421522]],

       [[10.59687086,  8.81358771, 15.40464332, 10.39030825],
        [13.10416067, 11.9337243 ,  7.37750935, 13.8306591 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [149]:
arr = np.random.uniform(1,16, size=(10))
print(arr)
arr=np.square(arr)
arr[arr < 0.5] = 0
arr

[ 4.35449646  5.71028644  4.30500955 11.51895207  1.19483692  9.33171009
  4.64533767 10.48706144  8.72736352  4.96799557]


array([ 18.96163942,  32.60737127,  18.53310721, 132.68625673,
         1.42763528,  87.08081327,  21.57916206, 109.97845763,
        76.166874  ,  24.68097998])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [152]:
arr1 = np.random.uniform(1,12, size=(10))
arr2 = np.random.uniform(1,12, size=(10))
arr3=np.maximum(arr1,arr2) 
arr3

array([ 3.99430531, 11.52556086, 11.90261062,  7.34436595,  7.99965035,
        6.02530692,  9.44389057, 11.37466304, 11.77282493, 10.89689442])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [157]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a=np.unique(names)
a=np.sort(a)
a


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [167]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
b=np.setdiff1d(a, b)
b

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [172]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [174]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [180]:
arr1 = np.random.random(size=(20))
np.sum(arr1)

10.2492236080684